version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/appserver/Dockerfile
    command: "uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 80"
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: "npm start"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: docker/pgsql/Dockerfile

  pgadmin:
    build:
      context: .
      dockerfile: docker/pgadmin/Dockerfile
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
