version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.appserver
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    container_name: fast_api
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - fast_api

  db:
    build:
      context: .
      dockerfile: Dockerfile.pgsql
    container_name: postgresql
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - fast_api

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - fast_api
    ports:
      - "8025:8025"
      - "1025:1025"

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - fast_api

volumes:
  pgadmin_volume:
  psql_volume:

networks:
  fast_api: