"""auth

Revision ID: 1abc8823a8e5
Revises: 81c112eb7981
Create Date: 2024-04-21 03:40:14.687201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1abc8823a8e5"
down_revision: Union[str, None] = "81c112eb7981"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
