"""books migration

Revision ID: 4bb1afd54edc
Revises:
Create Date: 2024-03-25 11:25:27.464124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bb1afd54edc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "books",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(), nullable=True),
    sa.Column("author", sa.String(), nullable=True),
    sa.Column("category", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
  op.create_index(op.f("ix_books_category"), "books", ["category"], unique=False)
  op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
  op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_books_title"), table_name="books")
  op.drop_index(op.f("ix_books_id"), table_name="books")
  op.drop_index(op.f("ix_books_category"), table_name="books")
  op.drop_index(op.f("ix_books_author"), table_name="books")
  op.drop_table("books")
  # ### end Alembic commands ###
