"""auth

Revision ID: 761ef4cf7454
Revises: 1abc8823a8e5
Create Date: 2024-04-21 03:53:06.172279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "761ef4cf7454"
down_revision: Union[str, None] = "1abc8823a8e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("roles", "user_id")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "roles", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
  )
  # ### end Alembic commands ###
