"""book

Revision ID: c1e3e65514d2
Revises: 0b2e48077fa0
Create Date: 2024-05-01 07:45:13.561796

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1e3e65514d2"
down_revision: Union[str, None] = "0b2e48077fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "books",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(), nullable=True),
    sa.Column("author", sa.String(), nullable=True),
    sa.Column("category", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_books_id"), table_name="books")
  op.drop_table("books")
  # ### end Alembic commands ###
