"""User migration

Revision ID: e1401c4c5ff6
Revises: 8bf811f61774
Create Date: 2024-03-27 11:28:02.712719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1401c4c5ff6"
down_revision: Union[str, None] = "8bf811f61774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("email", sa.String(), nullable=True),
    sa.Column("password", sa.String(), nullable=True),
    sa.Column("avatar", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_users_id"), table_name="users")
  op.drop_table("users")
  # ### end Alembic commands ###
